name: Keep alive the workflow for this entire repository
on:
  schedule:
    - cron: "0 0 * * 1"
  workflow_dispatch:

jobs:
  keep_alive:
    runs-on: ubuntu-latest
    steps:
      - uses: canonical/robotics-actions-workflows/.github/workflows/snap.yaml@main
        with:
          workflow_files: ./monthly.yaml

