name: Monthly
on:
  schedule:
    - cron: '0 0 1 * *'
  workflow_dispatch:

jobs:
  main-snap:
    uses: ubuntu-robotics/ros2-humble-talker-listener-snap/.github/workflows/snap.yaml@main
  confined-snap:
    uses: ubuntu-robotics/ros2-humble-talker-listener-snap/.github/workflows/snap.yaml@confined
  daemon-snap:
    uses: ubuntu-robotics/ros2-humble-talker-listener-snap/.github/workflows/snap.yaml@daemon
