name: snap
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
  workflow_call:

jobs:
  build-install-test-snap:
    runs-on: ubuntu-latest
    outputs:
      snap-file: ${{ steps.build-snap.outputs.snap }}
    steps:
    - uses: actions/checkout@v4
      with:
        ref: F_add_snap_info_check
    - uses: snapcore/action-build@v1
      id: build-snap
    - name: Install snap
      run: |
        sudo snap install ${{ steps.build-snap.outputs.snap }} --devmode
    - name: Check snap info command is equal to tutorial
      run: |
        bash .github/workflows/tests/info_equal_test.sh
    - uses: actions/upload-artifact@v3
      with:
        name: ros2-talker-listener-main
        path: ${{ steps.build-snap.outputs.snap }}
