name: snap
on:
  schedule:
    - cron: '0 0 1 * *'
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  main-snap:
    uses: ubuntu-robotics/snap_workflows/.github/workflows/build-install-test-snap.yaml@F_build_install_snap_workflow
    with:
      branch-name: main
      snap-name: ros2-talker-listener
  confined-snap:
    uses: ubuntu-robotics/snap_workflows/.github/workflows/build-install-test-snap.yaml@F_build_install_snap_workflow
    with:
      branch-name: confined
      snap-name: ros2-talker-listener
  daemon-snap:
    uses: ubuntu-robotics/snap_workflows/.github/workflows/build-install-test-snap.yaml@F_build_install_snap_workflow
    with:
      branch-name: daemon
      snap-name: ros2-talker-listener
