name: snap
on:
  schedule:
    - cron: '0 0 1 * *'
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  main-snap:
    uses: ubuntu-robotics/ros2-humble-talker-listener-snap/.github/workflows/build-install-upload-snap.yaml
    with:
      branch-name: main
      snap-name: ros2-talker-listener
  confined-snap:
    uses: ubuntu-robotics/ros2-humble-talker-listener-snap/.github/workflows/build-install-upload-snap.yaml
    with:
      branch-name: confined
      snap-name: ros2-talker-listener
  daemon-snap:
    uses: ubuntu-robotics/ros2-humble-talker-listener-snap/.github/workflows/build-install-upload-snap.yaml
    with:
      branch-name: daemon
      snap-name: ros2-talker-listener
