name: snap
on:
  push:
    branches:
      - daemon
  pull_request:
    branches:
      - daemon
  workflow_dispatch:
  workflow_call:

jobs:
  daemon-snap:
    uses: ubuntu-robotics/snap_workflows/.github/workflows/build-install-test-snap.yaml@main
    with:
      branch-name: daemon
      snap-name: ros2-talker-listener
