name: snap
on:
  push:
    tags:
      - '*'
    branches:
      - F_add_action_main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      snap-file: ${{ steps.build-snap.outputs.snap }}
    steps:
    - uses: actions/checkout@v2
    - uses: snapcore/action-build@v1
      id: build-snap

    # Make sure the snap is installable
    - run: |
        sudo snap install ${{ steps.build-snap.outputs.snap }} --devmode
    # Do some testing with the snap
    - run: |
        ros2-talker-listener
        snap info ros2-talker-listener
    - uses: actions/upload-artifact@v3
      with:
        name: ros2-talker-listener
        path: ${{ steps.build-snap.outputs.snap }}
