name: snap
on:
  push:
    branches:
      - daemon
  pull_request:
    branches:
      - daemon
  workflow_dispatch:
  workflow_call:

jobs:
  daemon-snap:
    uses: ubuntu-robotics/snap_workflows/.github/workflows/snap.yaml@main
    with:
      branch-name: daemon
      snap-name: ros2-talker-listener
      snap-install-args: --dangerous
      test-script: |
                    #!/bin/bash
                    ### test snap info consistency
                    info_expected_output="name:      ros2-talker-listener
                    summary:   ROS 2 Talker/Listener Example
                    publisher: --
                    license:   unset
                    description: |
                      This example launches a ROS 2 talker and listener.
                    services:
                      ros2-talker-listener: simple, enabled, active
                    refresh-date: today at 16:39 CEST
                    installed: 0.1 (x9) 64MB -"

                    snap_info_output=$(snap info ros2-talker-listener)
                    diff  <(echo "${info_expected_output%%refresh-date*}" ) <(echo "${snap_info_output%%refresh-date*}")
                    if [ $? -eq 0 ]; then
                        echo "Strings are equal until refresh-date"
                    else
                        echo "Strings are not equal until refresh-date"
                        exit 1
                    fi

                    ### test ros2-talker-listener snap executes correctly with logs command
                    sleep 5
                    output=$(sudo snap logs ros2-talker-listener)

                    # Check if both strings are present in the output
                    if [[ $output == *"[listener]: I heard: [Hello World:"* && $output == *"[talker]: Publishing: 'Hello World:"* ]]; then
                        echo "Logs are showing listener and talker"
                    else
                        echo "Listener and talker not present in the log"
                        exit 1
                    fi
